{
 "title": "MEE API Latency Dashboard",
 "tags": [
  "latency",
  "mee-nde",
  "performance"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Overall Latency Percentile line chart",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "{{service}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Overall Latency Percentile heatmap chart",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "{{service}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le)(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "{{span_name}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "{{span_name}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "{{span_name}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"mee-node\"}[5m])))",
     "legendFormat": "{{span_name}} P99"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"mee-node\"}[5m])) by (span_name)",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"mee-node\"}[5m]))",
     "legendFormat": "mee node "
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (service)(rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service=\"mee-node\"}[5m]))/sum by (service)(rate(traces_spanmetrics_calls_total{service=\"mee-node\"}[5m]))",
     "legendFormat": "mee node "
    }
   ]
  },
  {
   "title": "Latency Percentiles - /v1/explorer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{span_name=\"/v1/explorer\"}[5m])) by (le))",
     "legendFormat": "/v1/explorer P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{span_name=\"/v1/explorer\"}[5m])) by (le))",
     "legendFormat": "/v1/explorer P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_name=\"/v1/explorer\"}[5m])) by (le))",
     "legendFormat": "/v1/explorer P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{span_name=\"/v1/explorer\"}[5m])) by (le))",
     "legendFormat": "/v1/explorer P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - /v1/exec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\", span_name=\"/v1/exec\"}[5m])) by (le))",
     "legendFormat": "/v1/exec P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\", span_name=\"/v1/exec\"}[5m])) by (le))",
     "legendFormat": "/v1/exec P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\", span_name=\"/v1/exec\"}[5m])) by (le))",
     "legendFormat": "/v1/exec P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\", span_name=\"/v1/exec\"}[5m])) by (le))",
     "legendFormat": "/v1/exec P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - /v1/quote-permit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\", span_name=\"/v1/quote-permit\"}[5m])) by (le))",
     "legendFormat": "/v1/quote-permit P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote-permit\"}[5m])) by (le))",
     "legendFormat": "/v1/quote-permit P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote-permit\"}[5m])) by (le))",
     "legendFormat": "/v1/quote-permit P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote-permit\"}[5m])) by (le))",
     "legendFormat": "v1/quote-permit P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - /v1/info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/info\"}[5m])) by (le))",
     "legendFormat": "/v1/info P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/info\"}[5m])) by (le))",
     "legendFormat": "/v1/info P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/info\"}[5m])) by (le))",
     "legendFormat": "/v1/info P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/info\"}[5m])) by (le))",
     "legendFormat": "/v1/info P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - Simulation Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulationPhase\"}[5m])) by (le))",
     "legendFormat": "simulationPhase P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulationPhase\"}[5m])) by (le))",
     "legendFormat": "simulationPhase P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - /v1/quote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote\"}[5m])) by (le))",
     "legendFormat": "/v1/quote P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote\"}[5m])) by (le))",
     "legendFormat": "/v1/quote P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote\"}[5m])) by (le))",
     "legendFormat": "/v1/quote P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/v1/quote\"}[5m])) by (le))",
     "legendFormat": "/v1/quote P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - Gas estimator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.legacyGasPrice\"}[5m])) by (le))",
     "legendFormat": "legacyGasPrice P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.legacyGasPrice\"}[5m])) by (le))",
     "legendFormat": "legacyGasPrice P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.eip1559GasPrice\"}[5m])) by (le))",
     "legendFormat": "eip1559GasPrice P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.eip1559GasPrice\"}[5m])) by (le))",
     "legendFormat": "eip1559GasPrice P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.maxPriorityFeePerGas\"}[5m])) by (le))",
     "legendFormat": "maxPriorityFeePerGas P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.maxPriorityFeePerGas\"}[5m])) by (le))",
     "legendFormat": "maxPriorityFeePerGas P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.optimismL1GasPrice\"}[5m])) by (le))",
     "legendFormat": "optimismL1GasPrice P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.optimismL1GasPrice\"}[5m])) by (le))",
     "legendFormat": "optimismL1GasPrice P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.arbitrumL1GasPrice\"}[5m])) by (le))",
     "legendFormat": "arbitrumL1GasPrice P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"gasEstimator.arbitrumL1GasPrice\"}[5m])) by (le))",
     "legendFormat": "arbitrumL1GasPrice P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - Execution Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase\"}[5m])) by (le))",
     "legendFormat": "executionPhase P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase\"}[5m])) by (le))",
     "legendFormat": "executionPhase P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase.executeBlock\"}[5m])) by (le))",
     "legendFormat": "executionPhase.executeBlock P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase.executeBlock\"}[5m])) by (le))",
     "legendFormat": "executionPhase.executeBlock P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase.fastBlockTxReceipt\"}[5m])) by (le))",
     "legendFormat": "executionPhase.fastBlockTxReceipt P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase.fastBlockTxReceipt\"}[5m])) by (le))",
     "legendFormat": "executionPhase.fastBlockTxReceipt P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase.defaultBlockTxReceipt\"}[5m])) by (le))",
     "legendFormat": "executionPhase.defaultBlockTxReceipt P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"executionPhase.defaultBlockTxReceipt\"}[5m])) by (le))",
     "legendFormat": "executionPhase.defaultBlockTxReceipt P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - Payment providers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"paymentProvider.paymentRouteForArbitraryTokenSwap\"}[5m])) by (le))",
     "legendFormat": "paymentProvider.paymentRouteForArbitraryTokenSwap P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"paymentProvider.paymentRouteForArbitraryTokenSwap\"}[5m])) by (le))",
     "legendFormat": "paymentProvider.paymentRouteForArbitraryTokenSwap P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - Trace calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.simulateSimulateHandleOpWithEthCall\"}[5m])) by (le))",
     "legendFormat": "simulateSimulateHandleOpWithEthCall P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.simulateSimulateHandleOpWithEthCall\"}[5m])) by (le))",
     "legendFormat": "simulateSimulateHandleOpWithEthCall P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.estimateCallDataGas\"}[5m])) by (le))",
     "legendFormat": "estimateCallDataGas P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.estimateCallDataGas\"}[5m])) by (le))",
     "legendFormat": "estimateCallDataGas P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.simulateSimulateHandleOpWithDebugTraceCall\"}[5m])) by (le))",
     "legendFormat": "simulateSimulateHandleOpWithDebugTraceCall P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.simulateSimulateHandleOpWithDebugTraceCall\"}[5m])) by (le))",
     "legendFormat": "simulateSimulateHandleOpWithDebugTraceCall P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.simulateHandleOps\"}[5m])) by (le))",
     "legendFormat": "simulateHandleOps P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"entrypoint.simulateHandleOps\"}[5m])) by (le))",
     "legendFormat": "simulateHandleOps P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - Simulation Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.simulateAndEstimateGasForUserOps\"}[5m])) by (le))",
     "legendFormat": "simulateAndEstimateGasForUserOps P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.simulateAndEstimateGasForUserOps\"}[5m])) by (le))",
     "legendFormat": "simulateAndEstimateGasForUserOps P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.detectTokenBalanceStorageSlot\"}[5m])) by (le))",
     "legendFormat": "detectTokenBalanceStorageSlot P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.detectTokenBalanceStorageSlot\"}[5m])) by (le))",
     "legendFormat": "detectTokenBalanceStorageSlot P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.triggerTokenPullGasEstimation\"}[5m])) by (le))",
     "legendFormat": "triggerTokenPullGasEstimation P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.triggerTokenPullGasEstimation\"}[5m])) by (le))",
     "legendFormat": "triggerTokenPullGasEstimation P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.fetchPermitValues\"}[5m])) by (le))",
     "legendFormat": "fetchPermitValues P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.fetchPermitValues\"}[5m])) by (le))",
     "legendFormat": "fetchPermitValues P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.triggerTokenPermitGasEstimation\"}[5m])) by (le))",
     "legendFormat": "triggerTokenPermitGasEstimation P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"simulation.triggerTokenPermitGasEstimation\"}[5m])) by (le))",
     "legendFormat": "triggerTokenPermitGasEstimation P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - exec.simulateHandleOps -  exec.simulateSimulateHandleOp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateHandleOps\"}[5m])) by (le))",
     "legendFormat": "exec.simulateHandleOps P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateHandleOps\"}[5m])) by (le))",
     "legendFormat": "exec.simulateHandleOps P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateHandleOps\"}[5m])) by (le))",
     "legendFormat": "exec.simulateHandleOps P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateHandleOps\"}[5m])) by (le))",
     "legendFormat": "exec.simulateHandleOps P99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateSimulateHandleOp\"}[5m])) by (le))",
     "legendFormat": "exec.simulateSimulateHandleOp P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateSimulateHandleOp\"}[5m])) by (le))",
     "legendFormat": "exec.simulateSimulateHandleOp P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateSimulateHandleOp\"}[5m])) by (le))",
     "legendFormat": "exec.simulateSimulateHandleOp P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"exec.simulateSimulateHandleOp\"}[5m])) by (le))",
     "legendFormat": "exec.simulateSimulateHandleOp P99"
    }
   ]
  },
  {
   "title": "Latency Percentiles - /health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/health\"}[5m])) by (le))",
     "legendFormat": "/health P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/health\"}[5m])) by (le))",
     "legendFormat": "/health P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/health\"}[5m])) by (le))",
     "legendFormat": "/health P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"mee-node\",span_name=\"/health\"}[5m])) by (le))",
     "legendFormat": "/health P99"
    }
   ]
  }
 ]
}